export const registrationTypes = {
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS', SIGNUP_FAILURE: 'SIGNUP_FAILURE',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS', LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS', LOGOUT_FAILURE: 'LOGOUT_FAILURE',
	USER_LOADED: 'USER_LOADED',
	AUTH_ERROR: 'AUTH_ERROR'
};