export const COOKIE_ACCEPT = 'COOKIE_ACCEPT';

export const SET_TOAST = 'SET_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';

export const ADD_CATALOG_SUCCESS = 'ADD_CATALOG_SUCCESS';
export const ADD_CATALOG_FAILURE = 'ADD_CATALOG_FAILURE';

export const DELETE_CATALOG_SUCCESS = 'DELETE_CATALOG_SUCCESS';
export const DELETE_CATALOG_FAILURE = 'DELETE_CATALOG_FAILURE';

export const GET_CATALOGS_SUCCESS = 'GET_CATALOGS_SUCCESS';
export const GET_CATALOGS_FAILURE = 'GET_CATALOGS_FAILURE';

export const SET_CATALOG_EDITING = 'SET_CATALOG_EDITING';
export const STOP_CATALOG_EDITING = 'STOP_CATALOG_EDITING';

export const EDIT_CATALOG_SUCCESS = 'EDIT_CATALOG_SUCCESS';
export const EDIT_CATALOG_FAILURE = 'EDIT_CATALOG_FAILURE';
